# Generated by Django 2.0.9 on 2018-12-03 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0002_auto_20181129_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'CategoryTypes',
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DataPoints',
            },
        ),
        migrations.CreateModel(
            name='PerformedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object_collector.Action')),
            ],
            options={
                'verbose_name_plural': 'PerformedActions',
            },
        ),
        migrations.RenameModel(
            old_name='DataSourceType',
            new_name='DataPollingType',
        ),
        migrations.AlterModelOptions(
            name='datapollingtype',
            options={'verbose_name_plural': 'DataPollingTypes'},
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='data_source_type',
            new_name='data_polling_type',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object_collector.DataSource'),
        ),
        migrations.AddField(
            model_name='smartobject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_collector.CategoryType'),
        ),
    ]
