# Generated by Django 2.0.9 on 2018-12-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0005_action_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='entrypoint',
        ),
    ]
