# Generated by Django 2.0.9 on 2019-01-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0006_remove_datasource_entrypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='payload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object_collector.DataType'),
        ),
    ]
