# Generated by Django 2.0.9 on 2019-01-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0007_auto_20190107_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_collector.DataType'),
        ),
    ]
