# Generated by Django 2.0.9 on 2019-01-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0008_datatype_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='operator',
        ),
        migrations.AddField(
            model_name='datatype',
            name='operator',
            field=models.ManyToManyField(to='object_collector.Operator'),
        ),
    ]
