# Generated by Django 2.0.9 on 2019-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0008_auto_20190107_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
