# Generated by Django 2.0.9 on 2019-01-14 15:22

from django.db import migrations

def auto_add(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    DataType = apps.get_model("object_collector", "DataType")
    datatypes = DataType.objects.using(db_alias).filter(name = "boolean")
    if datatypes.count() == 0:
        DataType(name = "boolean").save()

    DataPollingType = apps.get_model("object_collector", "DataPollingType")
    datapollingtypes = DataPollingType.objects.using(db_alias).filter(name = "ON_REQUEST")
    if datapollingtypes.count() == 0:
        DataPollingType(name = "ON_REQUEST").save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0009_action_important'),
    ]

    operations = [migrations.RunPython(auto_add),
    ]
