# Generated by Django 2.0.9 on 2019-01-14 15:22

from django.db import migrations

def add_datatypes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    DataType = apps.get_model("object_collector", "DataType")
    datatypes_keys = ['boolean']
    datatypes = {k : DataType.objects.using(db_alias).filter(name = k) for k in datatypes_keys}
    for k in datatypes:
        if datatypes[k].count() == 0:
            DataType(name = k).save()

def add_datapollingtypes(apps, schema_editor):  
    db_alias = schema_editor.connection.alias 
    DataPollingType = apps.get_model("object_collector", "DataPollingType")
    datapollingtypes_keys = ['ON_REQUEST']
    datapollingtypes = {k : DataPollingType.objects.using(db_alias).filter(name = k) for k in datapollingtypes_keys}
    for k in datapollingtypes:
        if datapollingtypes[k].count() == 0:
            DataPollingType(name = k).save()


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0009_action_important'),
    ]

    operations = [migrations.RunPython(add_datatypes),
    migrations.RunPython(add_datapollingtypes),
    ]
