# Generated by Django 2.0.9 on 2019-01-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0010_actionscenario'),
        ('object_collector', '0009_action_important'),
    ]

    operations = [
    ]
