# Generated by Django 2.0.9 on 2019-01-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0011_merge_20190115_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionscenario',
            name='data_type',
            field=models.ForeignKey(default='number', on_delete=django.db.models.deletion.CASCADE, to='object_collector.DataType'),
            preserve_default=False,
        ),
    ]
