# Generated by Django 2.0.9 on 2019-01-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0012_actionscenario_data_type'),
        ('object_collector', '0010_auto_add_basic_entries'),
    ]

    operations = [
    ]
