# Generated by Django 2.0.9 on 2019-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0013_merge_20190118_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='operator',
        ),
        migrations.AddField(
            model_name='operator',
            name='allowedTypes',
            field=models.ManyToManyField(to='object_collector.DataType'),
        ),
    ]
