# Generated by Django 2.0.9 on 2019-01-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0014_auto_20190118_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='allowedTypes',
            new_name='allowed_types',
        ),
    ]
