# Generated by Django 2.0.10 on 2019-01-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0015_auto_20190118_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionscenario',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='action',
        ),
    ]
