# Generated by Django 2.0.9 on 2019-01-14 15:22

from django.db import migrations

def add_datatypes_operators(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Operator = apps.get_model("object_collector", "Operator") 
    DataType = apps.get_model("object_collector", "DataType")
    datatypes_keys = ['boolean', 'string', 'number']
    operators_keys = ['EQUAL', 'GT', 'GTE', 'LT', 'LTE']
    datatypes = {k : DataType.objects.using(db_alias).filter(name = k) for k in datatypes_keys}
    for k in datatypes:
        if datatypes[k].count() == 0:
            DataType(name = k).save()

    datatypes = {k : DataType.objects.using(db_alias).get(name = k) for k in datatypes_keys}
    operators = {k: Operator.objects.using(db_alias).filter(name = k) for k in operators_keys}
    for k in operators:
        if operators[k].count() == 0:
            op = Operator(name = k)
            op.save()            
            op.allowed_types.add(datatypes['number'])
            if k == 'EQUAL':
                for datatype in datatypes:
                    if datatype != 'number':
                        op.allowed_types.add(datatype)                   
        elif k == 'EQUAL' and operators[k].allowed_types.all().count() < 3:
            for datatype in datatypes:
                if operators[k].allowed_types.filter(name = datatype).count() == 0:
                    operators[k].allowed_types.add(datatypes[datatype])

def add_datapollingtypes(apps, schema_editor):  
    db_alias = schema_editor.connection.alias 
    DataPollingType = apps.get_model("object_collector", "DataPollingType")
    datapollingtypes_keys = ['ON_REQUEST', 'ON_PUSH']
    datapollingtypes = {k : DataPollingType.objects.using(db_alias).filter(name = k) for k in datapollingtypes_keys}
    for k in datapollingtypes:
        if datapollingtypes[k].count() == 0:
            DataPollingType(name = k).save()



class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0015_auto_20190118_1544'),
    ]

    operations = [migrations.RunPython(add_datatypes_operators),
    migrations.RunPython(add_datapollingtypes),
    ]
