# Generated by Django 2.0.9 on 2019-01-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0016_auto_add_basic_entries_operators'),
        ('object_collector', '0016_auto_20190121_1532'),
    ]

    operations = [
    ]
