# Generated by Django 2.0.9 on 2019-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0017_merge_20190121_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionscenario',
            name='payload',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
