# Generated by Django 2.0.9 on 2019-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_collector', '0019_auto_20190213_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartobject',
            name='address_ip',
            field=models.CharField(max_length=100),
        ),
    ]
